version: '3.0'

services:
  consul:
    image: consul
    ports:
      - 8500:8500
      - 8600:8600/udp
    environment:
      - CONSUL_BIND_INTERFACE=eth0

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
